version: '3'

services:
  nginx:
    build:
      context: docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/custom.conf:/etc/nginx/http.d/default.conf
      - ./docker/php-fpm/index.php:/var/www/index.php
    networks:
      - custom-net

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./docker/php-fpm/index.php:/var/www/index.php
    networks:
      - custom-net

networks:
  custom-net:
    driver: bridge